### PR TITLE
Add sequelize migrations example code

### PR DESCRIPTION
**Pull request by DesignByOnyx**
This code accompanies documentation added in feathers-docs. I will link the two when I open that PR.

### CODE REVIEW

**Comment by combsco** [comment]
This would move the model outside the service correct? If so, how would this work if you were to make the Author Service its own instance versus a monolith.

**Comment by ekryski** [comment]
@DesignByOnyx awesome! Thanks! 😄

**Comment by ekryski** [comment]
@combsco you can realistically put your models wherever you want as long as you have a way of registering them with `sequelize`. In my example I kept them in the same directory as the service. https://github.com/feathersjs/feathers-demos/blob/master/examples/app-structure/many-to-many-sequelize/src/services/user/index.js#L11

**Comment by ekryski** [comment]
I'll probably combine the two examples at some point so that people aren't confused but we're currently talking about making the generated app structure more friendly, so we'll clean up the examples after that is sorted.

**Comment by DesignByOnyx** [comment]
@combsco - I chose to decouple my models and services because I don't have a 1-to-1 relationship of services to models - sometimes I don't have a model for a service and other times I have services that interact with multiple models. As Eric pointed out it doesn't really matter where you have them. However, the migrations config expects that `app.get('models')` will return an object of model names -> Models. At some point your code should do the following:

```js
app.set('models', sequelize.models);
```

**Pull request merged**
